# woodpecker ci yaml file
when:
  - event: manual

steps:
  - name: build
    image: docker.io/library/golang:latest
    commands:
      - git config --global --add safe.directory /woodpecker/src
      - make
      - make check
  - name: release
    image: docker.io/library/golang:latest
    commands:
      - git config --global --add safe.directory /woodpecker/src
      - make releases
