version: 2
project_name: lockbox
builds:
  - main: cmd/lb/main.go
    env:
      - CGO_ENABLED=0
    binary: lb
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    formats: ['tar.gz']
    files:
      - none*
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
