# .goreleaser.yml
# Build customization
project_name: lockbox
builds:
  - main: cmd/main.go
    env:
      - CGO_ENABLED=0
    binary: lb
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    replacements:
      amd64: x86_64
      darwin: macos
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
