// Package kdbx requires fields for kdbx handling
// Code generated by generator; DO NOT EDIT.
package kdbx

const (
	// NotesField is the value of 'Notes' for kdbx files
	NotesField = "Notes"
	// OTPField is the value of 'otp' for kdbx files
	OTPField = "otp"
	// PasswordField is the value of 'Password' for kdbx files
	PasswordField = "Password"
	// URLField is the value of 'URL' for kdbx files
	URLField = "URL"
)

var (
	// AllFields are the kdbx fields
	AllFields = []string{
		NotesField,
		OTPField,
		PasswordField,
		URLField,
	}

	// AllFieldsLower are the kdbx fields lowercase
	AllFieldsLower = []string{
		"notes",
		"otp",
		"password",
		"url",
	}
)
