//go:generate go run kdbx.go
package main

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

var items = map[string]string{"Password": "", "OTP": "otp", "Notes": "", "URL": ""}

const fileTemplate = `// Package kdbx requires fields for kdbx handling
// Code generated by generator; DO NOT EDIT.
package kdbx

const (
{{- range . }}
	// {{ .Variable }} is the value of '{{ .Value }}' for kdbx files
	{{ .Variable }} = "{{ .Value }}"
{{- end }}
)

var (
	// AllFields are the kdbx fields
	AllFields = []string{
		{{- range . }}
		{{ .Variable }},
		{{- end }}
	}

	// AllFieldsLower are the kdbx fields lowercase
	AllFieldsLower = []string{
		{{- range . }}
		"{{ .Lower }}",
		{{- end }}
	}
)
`

type Item struct {
	Variable string
	Value    string
	Lower    string
}

func main() {
	var data []Item
	for k, v := range items {
		value := v
		if value == "" {
			value = k
		}
		data = append(data, Item{
			Variable: k + "Field",
			Value:    value,
			Lower:    strings.ToLower(value),
		})
	}
	slices.SortFunc(data, func(x, y Item) int {
		return strings.Compare(x.Lower, y.Lower)
	})

	f, err := os.Create(filepath.Join("..", "internal", "kdbx", "fields.go"))
	if err != nil {
		panic(err)
	}
	defer f.Close()

	tmpl := template.Must(template.New("gen").Parse(fileTemplate))
	tmpl.Execute(f, data)
}
