name: "build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v3
      - name: "deps"
        run: apk add go make git
      - name: "build"
        run: make build
      - name: "check"
        run: make check

